sudo: false
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  # https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  # Create test environment and install deps, prefer defaults, use bioconda when needed
  - conda create -n testenv python=$TRAVIS_PYTHON_VERSION numpy cython
  - source activate testenv
  - pip install -r requirements.txt
  - pip install -e .
script:
  - pytest
