name: fontanka
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - cython=0.29.24
  - matplotlib-base
  - pandas=1.5.3
  - proplot
  - python=3.8.12
  - scipy=1.10.1
  - numba=0.57.1
  - seaborn
  - ipykernel
  - tqdm
  - click-log
  - pip
  - pip:
    - numpy==1.23.5
    - bioframe==0.4.1
    - cooler==0.8.11
    - cooltools==0.5.2
    - multiprocess==0.70.12.2
    - scikit-learn==1.0
