name: fontanka
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python==3.10
  - cython==0.29.35
  - numpy==1.24.4
  - pip
  - pip:
    - matplotlib==3.4.3
    - pandas==2.0.3
    - scipy==1.11.1
    - seaborn==0.12.2
    - proplot==0.9.7
    - ipykernel==6.23.3
    - tqdm==4.65.0
    - multiprocess==0.70.14
    - scikit-learn==1.3.0
    - click==8.1.3
    - bioframe==0.4.1
    - cooler==0.9.2
    - cooltools==0.5.4
